### PR TITLE
feat: explicitly pull in grpc-js ~1.0.5

### PR DESCRIPTION
**Pull request by feywind**
Adds a direct dependency to grpc-js so we can pull in versions faster than gax, if needed. This is also correct (imo) because the Pub/Sub library is already directly referencing things in grpc-js.

Also bump us to ~1.0.5 so we get the fix for the stream write after end. Hopefully fixes https://github.com/googleapis/nodejs-pubsub/issues/825.

### CODE REVIEW

**Comment by alexander-fenster** [comment]
I don't feel too positive or too negative about that - there are pros and cons :)

**Comment by feywind** [comment]
After talking it over internally, I think I'm going to pause this and just put in a gax PR, and repurpose this one for pulling in the new gax.

**Comment by Sytten** [comment]
I hit a bug when I updated to v2: `../../node_modules/@google-cloud/pubsub/build/src/index.d.ts(77,30): error TS2307: Cannot find module '@grpc/grpc-js' or its corresponding type declarations.` Is this related?

**Comment by feywind** [comment]
Gax versions were updated by https://github.com/googleapis/nodejs-pubsub/pull/1085 so I'm going to go ahead and close this.
