### ISSUE TITLE
node_modules/@google-cloud/pubsub/build/src/message-stream.d.ts:83:5 - error TS2416: Property 'destroy' in type 'MessageStream' is not assignable to the same property in base type 'PassThrough'

### ISSUE THREAD

**Issue by skhaz** [googleapis/nodejs-pubsub#1459]
node_modules/@google-cloud/pubsub/build/src/message-stream.d.ts:83:5 - error TS2416: Property 'destroy' in type 'MessageStream' is not assignable to the same property in base type 'PassThrough'.
  Type '(error?: Error | null | undefined) => void' is not assignable to type '(error?: Error | undefined) => this'.
    Type 'void' is not assignable to type 'this'.
      'this' could be instantiated with an arbitrary type which could be unrelated to 'void'.

83     destroy(error?: Error | null): void;
       ~~~~~~~

**Comment by skhaz** [comment]
The error occurs when I upgraded `@types/node` from 17.0.5 to 17.0.8 (the current latest)

**Comment by skhaz** [comment]
The incompatible version is @types/node `17.0.5`

**Comment by CarltonK** [comment]
I have the same error with @types/node being 17.0.0

**Comment by CarltonK** [comment]
The issue was resolved when I upgraded @types/node to 17.0.5

**Comment by skhaz** [comment]
@CarltonK yes, the temporary workaround is pin @types/node to 17.0.5

**Comment by aabmass** [comment]
Also seeing it upgrading `@types/node` from 14.17.32 -> 14.18.5

**Comment by feywind** [comment]
Folding this into https://github.com/googleapis/nodejs-pubsub/issues/1451 - please check there for updates.
